### ISSUE TITLE
Failed to load `next.config.js` after updating to 0.0.29

### ISSUE THREAD

**Issue by jahirfiquitiva** [contentlayerdev/contentlayer#32]
```gradle
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '/Users/jahir/dev/jahir/folio/node_modules/next-contentlayer/dist/index-cjs.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
    at resolveExports (internal/modules/cjs/loader.js:449:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.mod._resolveFilename (/Users/jahir/dev/jahir/folio/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jahir/dev/jahir/folio/next.config.js:4:30) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/jahir/dev/jahir/folio/node_modules/next-contentlayer/package.json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jahirfiquitiva** [comment]
Could it be that after adding support for `next.config.mjs`, there's no longer support for `next.config.js`? 🤔

**Comment by jahirfiquitiva** [comment]
The `dev` version is working fine! ...
Thank you so much!

**Comment by schickling** [comment]
https://github.com/contentlayerdev/contentlayer/releases/tag/v0.0.30
